
import type { Metadata } from "next";
import SearchList from './searchList';


export const metadata: Metadata = {
  title: "language_practice_tool",
  description: "Generated by create next app",
};


const App: React.FC = () => {
  return (
    <div>
      {/* 这里是你的内容 */}
      <SearchList />
    </div>
  );
};
export default App;
